<?php

class ContactsModel extends MY_Model{


    public function __construct(){
        parent::__construct();
        $this->table = 'contacts';
    }

    public function getAll($sort = 'id', $order = 'asc', $mode = ReturnType::ARRAY, $class = null)
    {
        return parent::getAll($sort, $order, $mode, $class); // TODO: Change the autogenerated stub
    }
}
